### ISSUE TITLE
Providing db username and password config through console when running migrations

### ISSUE THREAD

**Issue by victorbstan** [emirotin/mongodb-migrations#11]
This is more of a question than an issue. Is there a way to provide the mongo username and password when running a migration through the console?

I know I can provide MONGO_HOST, MONGO_PORT and MONGO_DB. I would expect MONGO_USER and MONGO_PASSWORD would work as well, but they don't seem to. I've also tried USER and PASSWORD but that didn't seem to work either. How can I provide these variables?

example command:

`MONGO_HOST=example.mongodbdns.com MONGO_PORT=2000 MONGO_DB=staging MONGO_USER=root MONGO_PASSWORD=password node_modules/mongodb-migrations/bin/mm`

**Comment by victorbstan** [comment]
I just found this in mm-config.js file, I think this answers my question.
```
    "host": process.env.MONGO_HOST,
    "port": process.env.MONGO_PORT,
    "db": process.env.MONGO_DB,
    "user": process.env.MONGO_USER,
    "password": process.env.MONGO_PASS,
```

**Comment by emirotin** [comment]
Yeah looks like it really answers it :)
