### ISSUE TITLE
Unable to query collections inside migration script

### ISSUE THREAD

**Issue by harrybvp** [emirotin/mongodb-migrations#14]
I am trying to insert data by querying pre-existing collection in a migration script
However find on that collection is returning zero results.
this.`db.collection('some-existing-collection').find({}).exec(callback);`
callback is never getting executed

Infact `this.db.listCollections()` is also returning emoty array.
It seems existing collections are getting ignored.

**Comment by emirotin** [comment]
What Mongo version? Can you create a sample entire project where it's reproducible?

**Comment by harrybvp** [comment]
I am using mongod version: 3.0.7 and using mongodb-migrations 0.5.0
I will see if i can create a sample project.

**Comment by harrybvp** [comment]
while trying to reproduce the issue , I figured i was doing things incorrectly 
i was invoking done() method outside callback.
so done() line got executed immediately and async callback never get executed 

Thanks

**Comment by emirotin** [comment]
Nice to know you've solved it. I supposed something along that lines.
