### ISSUE TITLE
Chattier configuration errors

### ISSUE THREAD

**Issue by AllenSH12** [emirotin/mongodb-migrations#17]
First off thanks for the library guys, appreciate it.

Second, it seems like there could be some more useful error messages and/or defaults around configuration. For example:

```
# mm-config.json

{
  "host": "localhost",
  "port": "27017",
  "db": "test"
}
```

```
#1-foogration.js

module.exports.id = "FOOGRATION";

module.exports.up = function (done) {
  // use this.db for MongoDB communication, and this.log() for logging
  done();
};

module.exports.down = function (done) {
  // use this.db for MongoDB communication, and this.log() for logging
  done();
};
```

Now this doesn't actually change anything in the DB but when it's run it simply hangs, a connection is made to mongo but nothing is printed to the log.

```
mm migrate # and... nothing
```

As you may have noticed my config was missing the `collection` key, and adding it does solve the issue and result in a successful run but perhaps in these negative cases the library could communicate to the user, "hey you're missing some required config"?

Happy to add this functionality myself if requested, opening this issue in the meantime just to let you guys know.

Thanks again!

**Comment by emirotin** [comment]
Hey, thanks for reporting!
It's been a while since I had a chance to work with this library, unfortunately :\
You're completely right, there should be a default or an error thrown. A PR is welcome.

**Comment by gonsfx** [comment]
@emirotin may i ask what you use for migrations nowadays?

**Comment by emirotin** [comment]
I don't use MongoDB these days at all.

**Comment by emirotin** [comment]
I've returned to this module and made the following changes
- the collection param now defaults to `_migrations` which should be a safe default IMO
- other required config options are validated

This will be part of the 0.8.0 release to be published tonight.
