### ISSUE TITLE
Feature request: Callback timeout

### ISSUE THREAD

**Issue by alyyousuf7** [emirotin/mongodb-migrations#20]
First of all, great module! +1

When migrating, there could be a chance when the `done` callback function is not called at all for whatever reason. It would be nice to have a timeout when migration up with CLI.

I have a bash script which runs on every deployment of my server. In that script I also have `mm migrate`. If for some reasons, the `done` function is not called, the `mm migrate` just waits.

Setting a timeout in the config file would an awesome feature!

**Comment by emirotin** [comment]
Nice idea.
Unfortunately I can't guarantee I will have time for it in the nearest
future. If you're interested in sending a PR I'll be happy to review and
publish.

**Comment by emirotin** [comment]
Published as 0.6.2. Thanks for the contribution again.
