### ISSUE TITLE
Multiple Databases in migration

### ISSUE THREAD

**Issue by ulisesbocchio** [emirotin/mongodb-migrations#33]
Is there a way to do a migration that involves multiple databases? Or do I have to create multiple migrations?

**Comment by emirotin** [comment]
The module needs a single collection in a single DB as a source of truth about the migrations that have been ran. Other than that you can do virtually anything inside of your migration scripts, the library makes no assumptions. For your convenience the migrations code is given then connection to the same DB as this.db. You can use it or ignore, it's totally up to you.

So you can open N connection to other DBs on your own and run arbitrary commands.
I hope that answers your question.

**Comment by ulisesbocchio** [comment]
Ok, thanks!
