### ISSUE TITLE
How to down version?

### ISSUE THREAD

**Issue by balkarov** [emirotin/mongodb-migrations#43]
Hello!

I have version 1.0.
Now I added new properties to DataBase and release version 1.1.
I use your library for migration (thank you!).
But I do not fully understand, how roll away to version 1.0 after migration to 1.1?

I tried this:
```
...

var migrationDef = {
    id: "RenameProperty",
    up: function (done) {
        var coll = this.db.collection("GeneralSettings");
        coll.updateMany({}, {$rename: {"nmae": "name"}}, done);
    },
    down: function (done) {
        var coll = this.db.collection("GeneralSettings");
        coll.updateMany({}, {$rename: {"name": "nmae"}}, done);
    }
};

migrator.add(migrationDef);

migrator.rollback(function (error, results) {
    if (error)
        console.error(error);
    migrator.dispose(function () {
        console.log("DISCONNECTED!");
    });
    console.log(results);
});
```

But I get error:

> Error: Rollback can only be ran after migrate

Ok, after I tried this
```
...

migrator.add(migrationDef);

migrator.migrate(function (error, results) {
    if (error)
        console.error(error);
    migrator.rollback(function (error, results) {
        if (error)
            console.error(error);
        migrator.dispose(function () {
            console.log("DISCONNECTED!");
        });
        console.log(results);
    });
    console.log(results);
});
```

I get this

> Migration 'RenameProperty': skip (migration already ran)
{ RenameProperty: 
   { status: 'skip',
     reason: 'migration already ran',
     code: 'already_ran' } }
{ RenameProperty: 
   { status: 'skip',
     reason: 'migration already ran',
     code: 'already_ran' } }
DISCONNECTED!

How need use this migrator.rollback()?
Or I can use rollback only when migrate error?
Or I need manually write migration for rollback?

**Comment by emirotin** [comment]
Migrate is only for _rolling back_ (undoing) the changes right after applying them.

You wan to check this: https://github.com/emirotin/mongodb-migrations/issues/8
It's not released yet but you can use it from the git branch.
