### ISSUE TITLE
Support for replica sets?

### ISSUE THREAD

**Issue by codespelunker** [emirotin/mongodb-migrations#5]
I didn't see any support for replica set notation or multiple hosts.  We were able to get it working fine as long as we connected to our current primary node, but that node can change when there is a Mongo election.  Is there something I missed, or does it only have single-host support?

**Comment by eberhara** [comment]
Actually you can make it work on the current version of this project if all your mongos run on the default 27017 port.

Just put your replica set hosts on host param and add replicaset name at the end of db param, like:
module.exports = {
	host : 'host1,host2,hostN',
	db : 'your_db_name?replicaSet=your_replicaset'
}

A specific parameter for replicaset name would be great and way more elegant though. If we have that parameter, utils.coffee would just need to have the cmds below before returning the connection string:
if config.replicaSet
    s+= '?replicaSet=' + config.replicaSet

Hope it helps

**Comment by antony** [comment]
I believe I've addressed this in #19 and supported replicaset names as well as alternate ports. Let me know if this works for you.

**Comment by emirotin** [comment]
I've published version 0.6.0 just now, that includes this change from @antony, as well as some updates and refactoring (could result in slightly better performance). Please let me know how it works.
