### ISSUE TITLE
Consider using timestamps rather than incremental numbers...

### ISSUE THREAD

**Issue by michelob** [emirotin/mongodb-migrations#6]
Per the discussion here:
- https://github.com/tj/node-migrate/issues/2
- https://github.com/tj/node-migrate/pull/5

And similar issue here:
- https://github.com/afloyd/mongo-migrate/issues/23

Would you consider using time stamps as keys in mm.create instead of incremental numbers?

**Comment by emirotin** [comment]
I thought about this and I think it's a valid argument from TJ:

> if you have a conflict like that, chances are you likely need to reevaluate the migrations to make sure they dont conflict logically

Your thoughts?

**Comment by michelob** [comment]
Hi Eugene...

TJ relented in pull 5 (linked above) and the change was merged in. See the comments in pull 5 where more rationale is provided for using time stamps.

However, feel free to close this as no one else has asked for it. It's not at all a show stopper for me. I was considering the future, if multiple members where using the module on one project it could cause (very) small headaches.

-Mike

**Comment by emirotin** [comment]
Sorry it took me a bit to get back to the issues :(

I decided to close this finally. Will try to look into the other one today and expose the method to close the pending connections.

**Comment by jpgnotgif** [comment]
Hi Eugene,

I would like to request this feature 😄
