### ISSUE TITLE
How to close mongo connections after programatic runFromDir...

### ISSUE THREAD

**Issue by michelob** [emirotin/mongodb-migrations#7]
I'm using runFromDir programatically.

Despite pool config.max = 5 (which I see in your pool project), I'm seeing 25 connections after running runFromDir just before my server logic starts. And the connections don't close, so my app has left over connections from the migration run.

Is there a way to close these connections programatically after Migrator.runFromDir runs?

Thank you for this module, helped me a lot!
-M

**Comment by emirotin** [comment]
Nice to hear someone is actually using it :)

I should check how to close the connections. The supposed standard usage is obviously from the command line, that's why it wasn't an issue in my case. Will try to sort this out in a couple of days.

**Comment by michelob** [comment]
My use case is to...create migrations from the cmd line. Then call those programatically on app start up before anything else happens. If migrations fail, exit. If migrations are done and successful, then make my app own connections to the db and start up my app.

Fyi...none of the other mongo migrate type modules achieves this. So thankful for your work!

(As an aside, you can see above that I had 25 extra connections after running this in the way described above running db.serverStatus().connections. I can't seem to figure out why it's 25. I should have 5 extra, per your mongo pool sub module using 'max'. Don't know if you have a view as to why this is the case. But this mystery is not an issue if the mongo migrate runFromDir could close them.)

-Mike

**Comment by emirotin** [comment]
Thanks for more info. Will investigate the issue

**Comment by emirotin** [comment]
So first of all the reason why you have 25 connections is that the driver itself keeps a pool of 5 connections per client. Which probably means I should investigate it and stop using mongo-pool2.

Second, I've exposed the method to close connections here: https://github.com/emirotin/mongodb-migrations/tree/feature/expose-connection-close

Unfortunately I have troubles writing a test for it https://github.com/emirotin/mongodb-migrations/blob/feature/expose-connection-close/test/dispose.coffee which may be an issue with my tests or a potential problem highlight. 

Would be nice if you can give it a try and let me know if you have any troubles.

**Comment by michelob** [comment]
Hi Eugene...perfect...I've tested the branch. And the connections are now closed after run.

Thank you!

**Comment by emirotin** [comment]
Nice! Will release soon

**Comment by emirotin** [comment]
v0.3.1 released

**Comment by michelob** [comment]
Thank you! I've taken 0.3.1 and working as expected when calling dispose().

(I'm going to hold on 0.5.0 -- the change from mongopool2 up to mongodb 2.0 -- for just a bit.)

**Comment by emirotin** [comment]
Yep, would be nice if you can check 0.5, but be careful, it passes my tests, but if you use specific features of mongo driver 1.x it may not work for you as is. Though if it works it should probably have better performance and require less resources.
